### ISSUE TITLE
PRNG brute force exits immediately

### ISSUE THREAD

**Issue by djturuzzo** [wiire/pixiewps#31]
I cannot figure out if this is the expected functionality or there's something wrong with my `pixiewps` which does not seem to attempt brute force at all. It exists immediately even though it says it could take 30 mins.

```
[+] Running pixiewps with the information, wait ...
[Pixie-Dust]  
[Pixie-Dust]   Pixiewps 1.2
[Pixie-Dust]  
[Pixie-Dust]   [-] WPS pin not found!
[Pixie-Dust]  
[Pixie-Dust]   [*] Time taken: 0 s 59 ms
[Pixie-Dust]  
[+] Pin not found, trying -f (full PRNG brute force), this may take around 30 minutes
[Pixie-Dust]  
[Pixie-Dust]   Pixiewps 1.2
[Pixie-Dust]  
[Pixie-Dust]   [-] WPS pin not found!
[Pixie-Dust]
```

**Comment by wiire** [comment]
It shouldn't exit immediately, some possible reasons are:
- You're running an old version of the program. If you are, download it using the **clone or download** button in the main page (there's not a release yet for the latest commits)
- The time on your machine is set very close to 0 (Unix Epoch, 01/01/1970)

You can always use **make debug** instead of just **make** to compile it with _debug prints_ and see what's going on. Just be aware that it may break compatibility with some third party scripts.

Also, as a general note to everyone: it's been a very busy period for me and I had to set aside 'personal projects'. There are some changes and little features I wanted to add from a long time, as well as other projects I was working on left unfinished, but I simply don't have time right now.

**Comment by djturuzzo** [comment]
I will go through your suggestions and come back with feedback. Thank you.

**Comment by wiire** [comment]
I'm closing this for now. If you think there is indeed an issue, comment again what you're getting on output (after compiling with **make debug**) and the data you're testing it on.
